import sys
import numpy as np
import pandas as pd
from pathlib import Path
# App
from methylprep.processing import pipeline
from methylprep.utils.files import download_file
#patching
try:
    # python 3.4+ should use builtin unittest.mock not mock package
    from unittest.mock import patch
except ImportError:
    from mock import patch


class TestPipeline():

    @staticmethod
    def test_run_pipeline_all():
        """ check that we get back useful data.
        check that output files exist, then remove them."""
        test_data_dir = 'docs/example_data/GSE69852'
        test_outputs = [
            Path(test_data_dir, 'control_probes.pkl'),
            Path(test_data_dir, 'beta_values.pkl'),
            Path(test_data_dir, 'm_values.pkl'),
            Path(test_data_dir, 'meth_values.pkl'),
            Path(test_data_dir, 'unmeth_values.pkl'),
            Path(test_data_dir, 'noob_meth_values.pkl'),
            Path(test_data_dir, 'noob_unmeth_values.pkl'),
            Path(test_data_dir, 'sample_sheet_meta_data.pkl'),
            Path(test_data_dir, '9247377085', '9247377085_R04C02_processed.csv'),
            Path(test_data_dir, '9247377093', '9247377093_R02C01_processed.csv'),
            ]
        for outfile in test_outputs:
            if outfile.exists():
                outfile.unlink()

        beta_df = pipeline.run_pipeline(test_data_dir, export=True, save_uncorrected=True, save_control=True, betas=True, m_value=True, batch_size=None)
        for outfile in test_outputs:
            if not outfile.exists():
                raise FileNotFoundError(f"Expected {outfile.name} to be generated by run_pipeline() but it was missing.")
            else:
                print('+', outfile)
                outfile.unlink()

    @staticmethod
    def test_run_pipeline_demo_containers():
        """ check that we get back useful data.
        check that output files exist, then remove them."""
        test_data_dir = 'docs/example_data/GSE69852'
        test_data_containers = pipeline.run_pipeline(test_data_dir)
        print('containers:', test_data_containers)

        # spot checking the output.
        #if not test_data_containers[1].unmethylated.data_frame.iloc[0]['mean_value'] == 2712:
        if not np.isclose(test_data_containers[1]._SampleDataContainer__data_frame.iloc[0]['m_value'], -1.1347262):
            raise AssertionError()
        #if not np.isclose(test_data_containers[1].unmethylated.data_frame.iloc[0]['noob'], 4479.96501260212):
        if not np.isclose(test_data_containers[1]._SampleDataContainer__data_frame.iloc[0]['noob_unmeth'], 4480.919922):
            raise AssertionError()

    @staticmethod
    def test_run_pipeline_with_create_sample_sheet():
        test_data_dir = 'docs/example_data/epic_plus'
        test_data_containers = pipeline.run_pipeline(test_data_dir, export=False, sample_name=['Sample_1'],
            meta_data_frame=False, make_sample_sheet=True)
        # spot checking the output.
        if not np.isclose(test_data_containers[0]._SampleDataContainer__data_frame.iloc[0]['noob_meth'], 1180.22998046875):
            print(test_data_containers[0]._SampleDataContainer__data_frame)
            raise AssertionError(f"{test_data_containers[0]._SampleDataContainer__data_frame.iloc[0]['noob_meth']} vs {1180.2299}")
        if not np.isclose(test_data_containers[0]._SampleDataContainer__data_frame.iloc[0]['beta_value'], 0.759056):
            raise AssertionError()

    @staticmethod
    def test_download_manifest_dummy_file():
        """ will download a tiny file from the array-manifest-files s3 bucket, to test the SSL connection on all platforms.
        The dummy file is not a proper manifest CSV, so doesn't test format.
        download_file now defaults to non-SSL if SSL fails, with warning to user."""
        test_filename = 'unittest.txt'
        test_s3_bucket = 'https://array-manifest-files.s3.amazonaws.com'  # 's3://array-manifest-files'
        dest_dir = 'tests'
        # use the .download_file() method in files.py to test the download step specifically. this is called by Manifests() class.
        download_file(test_filename, test_s3_bucket, dest_dir, overwrite=False)
        # in testing mode, this should not exist, and should get deleted right after each successful test.
        if not Path(dest_dir,test_filename).is_file():
            raise AssertionError()
        Path(dest_dir,test_filename).unlink() # deletes file.

    @staticmethod
    def test_pipeline_two_samples():
        """ pass in --sample_name with 2 samples -- from fake command line args """
        test_data_dir = 'docs/example_data/GSE69852'
        testargs = ["__program__", '-d', test_data_dir, '--no_export', '--sample_name', 'AdultLiver1', 'FetalLiver1']
        with patch.object(sys, 'argv', testargs):
            test_data_containers = pipeline.run_pipeline(test_data_dir)
            # spot checking the output.
            #if not test_data_containers[1].unmethylated.data_frame.iloc[0]['mean_value'] == 2712:
            #if not test_data_containers[1]._SampleDataContainer__data_frame.iloc[0]['unmeth'] == 2712:
            #    raise AssertionError()
            if not np.isclose(test_data_containers[1]._SampleDataContainer__data_frame.iloc[0]['noob_unmeth'], 4480.919922):
                raise AssertionError()

    @staticmethod
    def test_run_pipeline_export_data():
        """ check that we get back useful data with --export option """
        test_data_dir = 'docs/example_data/GSE69852'
        testfile_1 = Path(test_data_dir, '9247377093', '9247377093_R02C01_processed.csv')
        testfile_2 = Path(test_data_dir, '9247377085', '9247377085_R04C02_processed.csv')
        if testfile_1.exists():
            testfile_1.unlink()
        if testfile_2.exists():
            testfile_2.unlink()
        test_data_containers = pipeline.run_pipeline(test_data_dir, export=True)
        if not testfile_1.exists():
            raise AssertionError("no exported processed csv found")

        test1 = pd.read_csv(testfile_1)
        if test1['beta_value'].isna().sum() > 0:
            print(test1.head())
            raise AssertionError('missing values in processed csv')
        test2 = pd.read_csv(testfile_2)
        if test2['beta_value'].isna().sum() > 0:
            print(test2.head())
            raise AssertionError('missing values in processed csv')

        # spot checking the output.
        if not np.isclose(test_data_containers[1]._SampleDataContainer__data_frame.iloc[0]['beta_value'], 0.30799999):
            print(test_data_containers[1]._SampleDataContainer__data_frame)
            raise AssertionError(f"{test_data_containers[1]._SampleDataContainer__data_frame.iloc[0]['beta_value']} vs {0.30799999}")
        # spot checking the output.
        total_nas = test_data_containers[0]._SampleDataContainer__data_frame['beta_value'].isna().sum()
        if total_nas > 0:
            print(f'found {total_nas} missing beta_values (N/A or inf) in sample')
            raise AssertionError()
        if not np.isclose(test_data_containers[1]._SampleDataContainer__data_frame.iloc[3]['noob_meth'], 3811.0):
            raise AssertionError(f"{test_data_containers[1]._SampleDataContainer__data_frame.iloc[3]['noob_meth']} vs {3811.162109}")

    @staticmethod
    def test_run_pipeline_epic_plus_export_data():
        """ check that we get back useful data with --export option """
        test_data_dir = 'docs/example_data/epic_plus'
        testfile_1 = Path(test_data_dir, '202651080072', '202651080072_R01C01_processed.csv')
        if testfile_1.exists():
            testfile_1.unlink()
        test_data_containers = pipeline.run_pipeline(test_data_dir, export=True)
        if not testfile_1.exists():
            raise AssertionError("no exported processed csv found")

        # spot checking the output.
        test1 = pd.read_csv(testfile_1)
        num_missing = test1['beta_value'].isna().sum()
        if num_missing == 1:
            if test1[test1.beta_value.isna()]['IlmnID'].iloc[0] == 'cg00968771_I_F_C_rep1_GWG1':
                print("WARNING: cg00968771_I_F_C_rep1_GWG1 probe data is STILL missing from output")
                #NOT A FATAL ERROR. but not fixing today.
        elif num_missing > 0:
            print(test1.head())
            raise AssertionError('{num_missing} missing values in processed csv')
        if not np.isclose(test1['beta_value'].iloc[5], 0.145):
            print(test1.iloc[5])
            raise AssertionError('beta_value doesnt match expected value')
        if not np.isclose(test_data_containers[0]._SampleDataContainer__data_frame.iloc[2]['noob_unmeth'], 284.0):
            print(test_data_containers[0]._SampleDataContainer__data_frame)
            raise AssertionError(f"data_container output ({test_data_containers[0]._SampleDataContainer__data_frame.iloc[2]['noob_unmeth']}) differs from expected value (284.0)")
