name: methylprep
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.16.3
  - pandas=0.24.2
  - scipy=1.2.1
  - statsmodels=0.9.0
  - autopep8
  - flake8
  - flake8
  - flake8
  - flake8
  - flake8
  - flake8
  - pep8
  - pylint
  - pytest
